### ISSUE TITLE
Add Chart to Repertory Button Not Working?

### ISSUE THREAD

**Issue by millsjdm** [barberscore/barberscore-api#555] opened 2019-06-24 19:56 UTC
Please check logic... competitors are not able to add charts... Chris checked with his group - same issue for him.

**Comment by dbinetti** [comment] 2019-06-24 20:27
Calling

**Comment by dbinetti** [comment] 2019-06-24 21:05
Regression caused by -- though not directly responsible for -- the detachment.  Fixed in 6c3229f9

**Closed by dbinetti** 2019-06-24 21:05 UTC
Labels: Intl
